name: deploy website
on:
  schedule:
    - cron:  '0 5 * * 3'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-args: '--prod' #Optional
          now-org-id: ${{ secrets.ZEIT_ORG_ID}}  #Required
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID}} #Required 
